server:
  port: 9999

spring:
  application:
    name: demo
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&tinyInt1isBit=false
    username: lsc
    password: lsc123456
  jpa:
    properties:
      hibernate:
        connection:
          url: ${spring.datasource.url}
          username: lsc
          password: lsc123456
      database: test
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    root: info